export interface Channel {
  id: string;
  name: string;
  logo: string;
  category: string;
  url: string;
}

export const channels: Channel[] = [
  {
    id: 'La1.es',
    name: 'La 1',
    logo: 'https://i.ibb.co/MxJNPHsn/La-1.png',
    category: 'Spain',
    url: 'https://rtvelivestream.rtve.es/rtvesec/la1/la1_main_dvr.m3u8',
  },
  {
    id: 'La2.es',
    name: 'La 2',
    logo: 'https://i.ibb.co/rfsr9PSh/La-2.png',
    category: 'Spain',
    url: 'https://rtvelivestream.rtve.es/rtvesec/la2/la2_main_dvr.m3u8',
  },
  {
    id: 'Antena3.es',
    name: 'Antena 3',
    logo: 'https://i.imgur.com/j3SP4BS.png',
    category: 'Spain',
    url: 'http://45.95.78.232:8001/udp/239.106.83.1:5000',
  },
  {
    id: 'Cuatro.es',
    name: 'Cuatro',
    logo: 'https://i.imgur.com/zROxNap.png',
    category: 'Spain',
    url: 'http://45.95.78.232:8001/udp/239.106.83.2:5000',
  },
  {
    id: 'Telecinco.es',
    name: 'Telecinco',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Telecinco_2024_Logo.svg/960px-Telecinco_2024_Logo.svg.png',
    category: 'Spain',
    url: 'http://45.95.78.232:8001/udp/239.106.83.3:5000',
  },
  {
    id: 'LaSexta.es',
    name: 'La Sexta',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/LaSexta_HD_Logo_2016.png/960px-LaSexta_HD_Logo_2016.png',
    category: 'Spain',
    url: 'http://45.95.78.232:8001/udp/239.106.83.4:5000',
  },
  {
    id: '24h.es',
    name: '24h',
    logo: 'https://i.ibb.co/21sXZ3GT/24h.png',
    category: 'Spain',
    url: 'https://ztnr.rtve.es/ztnr/1694255.m3u8',
  },
  {
    id: 'tdp.es',
    name: 'tdp',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/d/d1/TDP_2026.svg',
    category: 'Spain',
    url: 'https://rtvelivestream.rtve.es/rtvesec/tdp/tdp_main_dvr_360.m3u8',
  },
  {
    id: 'clan.es',
    name: 'clan',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/6/63/Clan_2026.svg',
    category: 'Spain',
    url: 'https://rtvelivestream.rtve.es/rtvesec/clan/clan_main_dvr.m3u8',
  },
  {
    id: 'TVEInternacionalEuropeAsia.es',
    name: 'TVE Internacional Europe-Asia',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e7/TVE.svg',
    category: 'Spain',
    url: 'https://rtvelivestream-rtveplayplus.rtve.es/rtvesec/int/tvei_eu_main_1080.m3u8',
  },
  {
    id: 'Neox.es',
    name: 'Neox',
    logo: 'https://raw.githubusercontent.com/tv-logo/tv-logos/refs/heads/main/countries/spain/neox-es.png',
    category: 'Spain',
    url: 'http://45.95.78.232:8001/udp/239.106.83.8:5000',
  },
  {
    id: 'Nova.es',
    name: 'Nova',
    logo: 'https://raw.githubusercontent.com/tv-logo/tv-logos/refs/heads/main/countries/spain/nova-es.png',
    category: 'Spain',
    url: 'http://40.160.24.55/Nova/index.m3u8',
  },
  {
    id: 'Mega.es',
    name: 'Mega',
    logo: 'https://i.imgur.com/Udrt2eK.png',
    category: 'Spain',
    url: 'http://45.95.78.232:8001/udp/239.106.84.5:5000',
  },
  {
    id: 'Atreseries.es',
    name: 'Atreseries',
    logo: 'https://raw.githubusercontent.com/tv-logo/tv-logos/refs/heads/main/countries/spain/atreseries-es.png',
    category: 'Spain',
    url: 'http://45.95.78.232:8001/udp/239.106.85.4:5000',
  },
  {
    id: 'FactoriadeFiccion.es',
    name: 'FDF',
    logo: 'https://raw.githubusercontent.com/tv-logo/tv-logos/refs/heads/main/countries/spain/fdf-es.png',
    category: 'Spain',
    url: 'http://45.95.78.232:8001/udp/239.106.83.7:5000',
  },
  {
    id: 'TRECE.es',
    name: 'TRECE',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Trece.svg/960px-Trece.svg.png',
    category: 'Spain',
    url: 'http://45.95.78.232:8001/udp/239.106.84.7:5000',
  },
  {
    id: 'Divinity.es',
    name: 'Divinity',
    logo: 'https://i.imgur.com/o7fvEr6.png',
    category: 'Spain',
    url: 'http://45.95.78.232:8001/udp/239.106.83.5:5000',
  },
  {
    id: 'Energy.es',
    name: 'Energy',
    logo: 'https://raw.githubusercontent.com/tv-logo/tv-logos/refs/heads/main/countries/spain/energy-es.png',
    category: 'Spain',
    url: 'http://45.95.78.232:8001/udp/239.106.84.4:5000',
  },
  {
    id: 'Boing.es',
    name: 'Boing',
    logo: 'https://i.imgur.com/nUYuCAP.png',
    category: 'Spain',
    url: 'http://185.189.225.150:85/boing/index.m3u8',
  },
  {
    id: 'Cartoon.network',
    name: 'Cartoon Network',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Cartoon_Network_2010_logo.svg/960px-Cartoon_Network_2010_logo.svg.png',
    category: 'Spain',
    url: 'http://38.41.8.1:8000/play/a11n',
  },
  {
    id: 'Nickelodeon.es',
    name: 'Nickelodeon',
    logo: 'https://logos-world.net/wp-content/uploads/2021/11/Nickelodeon-Logo.png',
    category: 'Spain',
    url: 'http://185.189.225.150:85/nickelodeon/index.m3u8',
  },
  {
    id: 'NickelodeonJr.es',
    name: 'Nick Jr',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nick_Jr._logo_2023_(outline).svg/960px-Nick_Jr._logo_2023_(outline).svg.png',
    category: 'Spain',
    url: 'http://thevdm.xyz:25461/live/timmadden/timmad4765/19942.m3u8',
  },
  {
    id: 'DisneyJr.es',
    name: 'Disney Jr',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/2024_Disney_Jr._Logo.svg',
    category: 'Spain',
    url: 'http://23.227.133.2:25461/live/timmadden/timmad4765/19878.m3u8',
  },
  {
    id: 'BeMad.es',
    name: 'Be Mad',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Be_Mad_TV.svg/960px-Be_Mad_TV.svg.png',
    category: 'Spain',
    url: 'http://45.95.78.232:8001/udp/239.106.85.1:5000',
  },
  {
    id: 'ParamountNetwork.es',
    name: 'Paramount Network',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Paramount_Network.svg/960px-Paramount_Network.svg.png',
    category: 'Spain',
    url: 'https://cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv/v2/stitch/hls/channel/68d566603d3a9580eb461251/master.m3u8?advertisingId=&appName=web&appVersion=7.9.0-a9cca6b89aea4dc0998b92a51989d2adb9a9025d&app_name=web&clientDeviceType=0&clientID=your_unique_uuid_here&clientModelNumber=1.0.0&country=ES&deviceDNT=false&deviceId=your_unique_uuid_here&deviceLat=40.4200&deviceLon=-3.6800&deviceMake=Chrome&deviceModel=web&deviceType=web&deviceVersion=16.2.0&marketingRegion=ES&serverSideAds=true&sessionID=8049f110-1949-11f1-8e13-429fdea1f0c4&sid=8049f110-1949-11f1-8e13-429fdea1f0c4&userId=&jwt=eyJhbGciOiJIUzI1NiIsImtpZCI6ImJiYTFiNmY1LWZlOTktNGEzNS04YTZjLWY2ZThhOWQyOWM2YyIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSUQiOiI4MDQ5ZjExMC0xOTQ5LTExZjEtOGUxMy00MjlmZGVhMWYwYzQiLCJjbGllbnRJUCI6IjgyLjk4LjEzNC4xMCIsImNpdHkiOiJNYWRyaWQiLCJwb3N0YWxDb2RlIjoiMjgwMDEiLCJjb3VudHJ5IjoiRVMiLCJkbWEiOjAsImFjdGl2ZVJlZ2lvbiI6IkVTIiwiZGV2aWNlTGF0Ijo0MC40MTk5OTgxNjg5NDUzMSwiZGV2aWNlTG9uIjotMy42ODAwMDAwNjY3NTcyMDIsInByZWZlcnJlZExhbmd1YWdlIjoiZW4iLCJkZXZpY2VUeXBlIjoid2ViIiwiZGV2aWNlVmVyc2lvbiI6IjE2LjIuMCIsImRldmljZU1ha2UiOiJDaHJvbWUiLCJkZXZpY2VNb2RlbCI6IndlYiIsImFwcE5hbWUiOiJ3ZWIiLCJhcHBWZXJzaW9uIjoiNy45LjAtYTljY2E2Yjg5YWVhNGRjMDk5OGI5MmE1MTk4OWQyYWRiOWE5MDI1ZCIsImNsaWVudElEIjoieW91cl91bmlxdWVfdXVpZF9oZXJlIiwiY21BdWRpZW5jZUlEIjoiIiwiaXNDbGllbnRETlQiOmZhbHNlLCJ1c2VySUQiOiIiLCJsb2dMZXZlbCI6IkRFRkFVTFQiLCJ0aW1lWm9uZSI6IkV1cm9wZS9NYWRyaWQiLCJzZXJ2ZXJTaWRlQWRzIjp0cnVlLCJlMmVCZWFjb25zIjpmYWxzZSwiZmVhdHVyZXMiOnsibXVsdGlQb2RBZHMiOnsiY29ob3J0IjoiIiwiZW5hYmxlZCI6dHJ1ZX0sInN0aXRjaGVySGxzTmciOnsiZGVtdXhlZEF1ZGlvIjoiaml0In19LCJmbXNQYXJhbXMiOnsiZndWY0lEMiI6InlvdXJfdW5pcXVlX3V1aWRfaGVyZSIsImZ3VmNJRDJDb3BwYSI6InlvdXJfdW5pcXVlX3V1aWRfaGVyZSIsImN1c3RvbVBhcmFtcyI6eyJmbXNfbGl2ZXJhbXBfaWRsIjoiIiwiZm1zX2VtYWlsaGFzaCI6IiIsImZtc19zdWJzY3JpYmVyaWQiOiIiLCJmbXNfaWZhIjoiIiwiZm1zX2lkZnYiOiIiLCJmbXNfdXNlcmlkIjoieW91cl91bmlxdWVfdXVpZF9oZXJlIiwiZm1zX3ZjaWQydHlwZSI6InVzZXJpZCIsImZtc19yYW1wX2lkIjoiIiwiZm1zX2hoX3JhbXBfaWQiOiIiLCJmbXNfYmlkaWR0eXBlIjoiIiwiX2Z3XzNQX1VJRCI6IiIsImZtc19ydWxlaWQiOiIxMDAxNiwxMDAyMCwxMDAyMSwxMDAyMywxMDAwMCwxMDAxMywxMDAxNCwxMDAxNSwxMDAwOSJ9fSwic2Vzc2lvblN0YXJ0VGltZSI6MTc3Mjc5Mzg5MDA4MywiaXNzIjoiYm9vdC5wbHV0by50diIsInN1YiI6InByaTp2MTpwbHV0bzpkZXZpY2VzOkVTOmVXOTFjbDkxYm1seGRXVmZkWFZwWkY5b1pYSmwiLCJhdWQiOiIqLnBsdXRvLnR2IiwiZXhwIjoxNzcyODgwMjkwLCJpYXQiOjE3NzI3OTM4OTAsImp0aSI6IjNiZWVkMDAxLWU2NjItNDNiNi04NWZlLWVhMzE5OTg2MmU4MCJ9.0jQ6ObCwr16FiYHRSJnXZ_yHrcorUspzyPEPPITkCjI&masterJWTPassthrough=true',
  },
  {
    id: 'Euronews.es',
    name: 'euronews',
    logo: 'https://raw.githubusercontent.com/tv-logo/tv-logos/refs/heads/main/countries/international/euro-news-int.png',
    category: 'Spain',
    url: 'https://euronews-live-spa-es.fast.rakuten.tv/v1/master/0547f18649bd788bec7b67b746e47670f558b6b2/production-LiveChannel-6571/bitok/eyJzdGlkIjoiMDA0YjY0NTMtYjY2MC00ZTZkLTlkNzEtMTk3YTM3ZDZhZWIxIiwibWt0IjoiZXMiLCJjaCI6NjU3MSwicHRmIjoxfQ==/26034/euronews-es.m3u8',
  },
  {
    id: 'ElPaisTV.es',
    name: 'El País',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/El_Pais_logo_2007.svg/960px-El_Pais_logo_2007.svg.png',
    category: 'Spain',
    url: 'https://d2epgk1fomaa1g.cloudfront.net/v1/manifest/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-9n8y4tw0bk3an/cb9a779f-4b18-4c54-a948-291d8a1cc8ea/0.m3u8',
  },
  {
    id: 'Qwesttv.us',
    name: 'Quest tv',
    logo: 'https://upload.wikimedia.org/wikipedia/en/4/42/Quest_logo_2014.svg',
    category: 'Spain',
    url: 'https://qwestjazz-rakuten.amagi.tv/hls/amagi_hls_data_rakutenAA-qwestjazz-rakuten/CDN/master.m3u8',
  },
  {
    id: 'NegociosTV.es',
    name: 'Negocios',
    logo: 'https://pbs.twimg.com/profile_images/1321367703731523584/bNMmbetI_200x200.jpg',
    category: 'Spain',
    url: 'https://streaming013.gestec-video.com/hls/negociostv.m3u8',
  },
  {
    id: 'Comedycentral.es',
    name: 'Comedy Central',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Comedy_Central_2018.svg/960px-Comedy_Central_2018.svg.png',
    category: 'Spain',
    url: 'http://38.96.178.201:80/live/ComedyCentral/index.m3u8',
  },
  {
    id: 'AMC.es',
    name: 'AMC',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/AMC_logo_2019.svg/960px-AMC_logo_2019.svg.png',
    category: 'Spain',
    url: 'http://vegafibratv.com:8085/AMC/index.m3u8',
  },
  {
    id: 'DISCOVERY.es',
    name: 'Discovery',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/2019_Discovery_logo.svg/960px-2019_Discovery_logo.svg.png',
    category: 'Spain',
    url: 'http://vegafibratv.com:8085/AMC/index.m3u8',
  },
  {
    id: 'Historia.es',
    name: 'Historia',
    logo: 'https://i.imgur.com/VUy8xIG.png',
    category: 'Spain',
    url: 'https://d1k3vzh2ivy22k.cloudfront.net/Historia.m3u8',
  },
  {
    id: 'AXN.es',
    name: 'AXN',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/AXN_logo_%282015%29.svg/960px-AXN_logo_%282015%29.svg.png',
    category: 'Spain',
    url: 'http://cdn.haititivi.com/AXN/index.m3u8',
  },
  {
    id: 'Squirrel.es',
    name: 'Squirrel',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Squirrel_TV_logo.svg/960px-Squirrel_TV_logo.svg.png',
    category: 'Spain',
    url: 'http://45.95.78.232:8001/udp/239.106.84.2:5000',
  },
  {
    id: 'Squirrel2.es',
    name: 'Squirrel DOS',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Nuevo_Logo_de_Squirrel_2_en_2026.svg/960px-Nuevo_Logo_de_Squirrel_2_en_2026.svg.png',
    category: 'Spain',
    url: 'http://45.95.78.232:8001/udp/239.106.84.3:5000',
  },
  {
    id: 'BomCine.es',
    name: 'BOM Cine',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Logo-bom.svg/960px-Logo-bom.svg.png',
    category: 'Spain',
    url: 'http://176.65.146.237:8401/play/a09d/index.m3u8',
  },
  {
    id: 'Telemadrid.es',
    name: 'Telemadrid',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/TeleMadrid.svg/960px-TeleMadrid.svg.png',
    category: 'Spain',
    url: 'https://live.telemadrid.cross-media.es/6389770581112/eu-central-1/6416060453001/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJob3N0IjoiajI5YjgyLmVncmVzcy5haGc3NmwiLCJhY2NvdW50X2lkIjoiNjQxNjA2MDQ1MzAwMSIsImVobiI6ImxpdmUudGVsZW1hZHJpZC5jcm9zcy1tZWRpYS5lcyIsImlzcyI6ImJsaXZlLXBsYXliYWNrLXNvdXJjZS1hcGkiLCJzdWIiOiJwYXRobWFwdG9rZW4iLCJhdWQiOlsiNjQxNjA2MDQ1MzAwMSJdLCJqdGkiOiI2Mzg5NzcwNTgxMTEyIn0.kqriAMUkHT6m0V6wkCHJum_EUyL4PAi1zJMKlfmYHEU/chunklist_audio0.m3u8',
  },
  {
    id: 'LaOtra.es',
    name: 'La Otra',
    logo: 'https://i.imgur.com/W1UZyXH.png',
    category: 'Spain',
    url: 'http://45.95.78.232:8001/udp/239.106.90.4:5000',
  },
  {
    id: 'CanalSurAndalucia.es',
    name: 'Canal Sur Andalucía',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/CanalSur1.svg/960px-CanalSur1.svg.png',
    category: 'Spain',
    url: 'https://dfk2a268yviz9.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-ddiii1m6jt6of/CanalSurAndaluciaES.m3u8',
  },
  {
    id: 'CanalSurAndaluciados.es',
    name: 'Canal Sur Andalucía 2',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Canal_Sur_2_-_2017_logo.png',
    category: 'Spain',
    url: 'https://cdnlive.codev8.net/rtvalive/smil:channel22.smil/playlist.m3u8',
  },
  {
    id: 'TENCanal10.hn',
    name: 'TEN',
    logo: 'https://i.imgur.com/HQiKyHy.jpg',
    category: 'Spain',
    url: 'http://45.95.78.232:8001/udp/239.106.85.2:5000',
  },
  {
    id: 'La8Mediterraneo.es',
    name: 'La 8 Mediterráneo',
    logo: 'https://graph.facebook.com/la8mediterraneo/picture?width=200&height=200',
    category: 'Spain',
    url: 'http://45.95.78.232:8001/udp/239.106.91.2:5000',
  },
  {
    id: 'TVCanaria.es',
    name: 'Televisión Canaria',
    logo: 'https://i.imgur.com/68LNS8e.png',
    category: 'Spain',
    url: 'https://www.youtube.com/user/TelevisionCanaria/live',
  },
  {
    id: 'IB3.es',
    name: 'IB3 Global',
    logo: 'https://raw.githubusercontent.com/tv-logo/tv-logos/refs/heads/main/countries/spain/ib3-es.png',
    category: 'Spain',
    url: 'https://www.youtube.com/c/ib3/live',
  },
  {
    id: 'CanalExtremadura.es',
    name: 'Canal Extremadura',
    logo: 'https://i.imgur.com/xBeywIA.png',
    category: 'Spain',
    url: 'http://45.95.78.232:8001/udp/239.106.90.6:5000',
  },
  {
    id: 'AragonTV.es',
    name: 'Aragón TV',
    logo: 'https://i.imgur.com/8H3Q07b.png',
    category: 'Spain',
    url: 'https://streamer95.server.aranova.cloud/clsdvr/live/aragontv_canal1/index.m3u8?vv=ES&h=grSocEHte5dddpuRxF1MbQ&e=31373831303035343530&r=2345',
  },
  {
    id: 'ETB1.es',
    name: 'ETB1',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/ETB1_2022_logo.svg/960px-ETB1_2022_logo.svg.png',
    category: 'Spain',
    url: 'https://multimedia.eitb.eus/live-content/etb1hd-hls/master.m3u8',
  },
  {
    id: 'ETB2.es',
    name: 'ETB2',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/ETB2_2022_logo.svg/960px-ETB2_2022_logo.svg.png',
    category: 'Spain',
    url: 'https://multimedia.eitb.eus/live-content/etb2hd-hls/master.m3u8',
  },
  {
    id: 'TV3.es',
    name: 'TV3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/TV3.svg/960px-TV3.svg.png',
    category: 'Spain',
    url: 'https://directes3-tv-cat.3catdirectes.cat/live-content/tv3-hls/master.m3u8',
  },
  {
    id: 'TV3CAT.es',
    name: 'TV3Cat',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/TV3CAT.svg/960px-TV3CAT.svg.png',
    category: 'Spain',
    url: 'https://directes3-tv-int.3catdirectes.cat/live-content/tvi-hls/master.m3u8',
  },
  {
    id: '324.es',
    name: '3/24',
    logo: 'https://raw.githubusercontent.com/tv-logo/tv-logos/refs/heads/main/countries/spain/3-24-es.png',
    category: 'Spain',
    url: 'https://directes-tv-int.3catdirectes.cat/live-origin/canal324-hls/master.m3u8',
  },
  {
    id: 'BonDiaTV.es',
    name: 'Bon Dia',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/4/4f/Logo_Bon_Dia_TV.png',
    category: 'Spain',
    url: 'https://directes-tv-int.3catdirectes.cat/live-content/bondia-hls/master.m3u8',
  },
  {
    id: 'SX3.es',
    name: 'SX3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/SX3_logo.svg/960px-SX3_logo.svg.png',
    category: 'Spain',
    url: 'https://directes-tv-cat.3catdirectes.cat/live-content/super3-hls/master.m3u8',
  },
  {
    id: 'El33.es',
    name: 'El 33',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/33_%28CCMA%29.svg/960px-33_%28CCMA%29.svg.png',
    category: 'Spain',
    url: 'https://directes-tv-cat.3catdirectes.cat/live-origin/c33-super3-hls/master.m3u8',
  },
  {
    id: 'Esport3.es',
    name: 'Esport3',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Esport3.svg/960px-Esport3.svg.png',
    category: 'Spain',
    url: 'https://directes-tv-es.3catdirectes.cat/live-origin/esport3-hls/master.m3u8',
  },
  {
    id: 'CanalTerresdelEbre.es',
    name: 'Canal TE24',
    logo: 'https://i.ibb.co/3ynghbW/logox2.png',
    category: 'Spain',
    url: 'https://ingest1-video.streaming-pro.com/esportsteABR/etestream/playlist.m3u8',
  },
  {
    id: 'APunt.es',
    name: 'À Punt TV',
    logo: 'https://i.imgur.com/M88LoNl.png',
    category: 'Spain',
    url: 'https://fastly.live.brightcove.com/1846756479408303045/eu-central-1/6057955885001/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJob3N0IjoiZWFxNWh4LmVncmVzcy53YzQ3bTEiLCJhY2NvdW50X2lkIjoiNjA1Nzk1NTg4NTAwMSIsImVobiI6ImZhc3RseS5saXZlLmJyaWdodGNvdmUuY29tIiwiaXNzIjoiYmxpdmUtcGxheWJhY2stc291cmNlLWFwaSIsInN1YiI6InBhdGhtYXB0b2tlbiIsImF1ZCI6WyI2MDU3OTU1ODg1MDAxIl0sImp0aSI6IjE4NDY3NTY0Nzk0MDgzMDMwNDUifQ.o6wb_VA-TVxl3ERgr7FKLlaTjY7smErmsf73QAydySE/playlist-hls-dvr.m3u8',
  },
  {
    id: 'TVCastello.es',
    name: 'TV Castelló',
    logo: 'https://www.tvcs.tv/wp-content/uploads/2022/07/logo.svg',
    category: 'Spain',
    url: 'https://fa723fc1b171.us-west-2.playback.live-video.net/api/video/v1/us-west-2.196233775518.channel.aMwy8tuUClSS.m3u8?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzM4NCJ9.eyJhd3M6Y2hhbm5lbC1hcm4iOiJhcm46YXdzOml2czp1cy13ZXN0LTI6MTk2MjMzNzc1NTE4OmNoYW5uZWwvYU13eTh0dVVDbFNTIiwiYXdzOmFjY2Vzcy1jb250cm9sLWFsbG93LW9yaWdpbiI6Imh0dHBzOi8va2ljay5jb20saHR0cHM6Ly93d3cuZ3N0YXRpYy5jb20saHR0cHM6Ly8qLmtpY2subGl2ZSxodHRwczovL3BsYXllci5raWNrLmNvbSxodHRwczovL2FkbWluLmtpY2suY29tLGh0dHBzOi8vYmV0YS5raWNrLmNvbSxodHRwczovL25leHQua2ljay5jb20saHR0cHM6Ly9kYXNoYm9hcmQua2ljay5jb20saHR0cHM6Ly8qLnByZXZpZXcua2ljay5jb20saHR0cHM6Ly94Ym94LmtpY2suY29tLGh0dHBzOi8vcGxheXN0YXRpb24ua2ljay5jb20saHR0cHM6Ly8qLmtpY2stcHJlcHJvZHVjdGlvbi5jb20saHR0cHM6Ly8qLmtpY2stZGV2ZWxvcG1lbnQuY29tIiwiYXdzOnN0cmljdC1vcmlnaW4tZW5mb3JjZW1lbnQiOmZhbHNlLCJhd3M6YWRzLW9wdC1vdXQiOnRydWUsImV4cCI6MTc3MzQ0MjM2M30.xpMcyXYFqB-YlhejQSjGKOLH44_FQNM99n6WbilSpXiGtCrsnb0F7mVbHrDVxV9QbdVtERRnxDFF8sYSddd7v5ePCUKwDoWMqxywebgnyRUB7kZC98ejHd2naz5Y8In8',
  },
  {
    id: 'La7.es',
    name: '7 Región de Murcia',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/La_7_logo.svg/960px-La_7_logo.svg.png',
    category: 'Spain',
    url: 'http://45.95.78.232:8001/udp/239.106.85.5:5000',
  },
  {
    id: 'Canal4Tenerife.es',
    name: 'Canal 4 Tenerife',
    logo: 'https://i.imgur.com/Egymir4.png',
    category: 'Spain',
    url: 'https://videoserver.tmcreativos.com:19360/ccxwhsfcnq/ccxwhsfcnq.m3u8',
  },
  {
    id: 'TelevisionMelilla.es',
    name: 'Televisión Melilla',
    logo: 'https://raw.githubusercontent.com/tv-logo/tv-logos/refs/heads/main/countries/spain/television-melilla-es.png',
    category: 'Spain',
    url: 'https://tvmelilla-hls-rm-lw.flumotion.com/playlist.m3u8',
  },
  {
    id: 'La1Catalunya.es',
    name: 'La 1 (Catalunya)',
    logo: 'https://i.ibb.co/MxJNPHsn/La-1.png',
    category: 'Spain',
    url: 'https://ztnr.rtve.es/ztnr/3293681.m3u8',
  },
  {
    id: 'La1Canarias.es',
    name: 'La 1 (Canarias)',
    logo: 'https://i.ibb.co/MxJNPHsn/La-1.png',
    category: 'Spain',
    url: 'https://ztnr.rtve.es/ztnr/5190066.m3u8',
  },
  {
    id: 'La2Catalunya.es',
    name: 'La 2 (Catalunya)',
    logo: 'https://i.ibb.co/Lztt9rgr/La-2-Catalunya.png',
    category: 'Spain',
    url: 'https://ztnr.rtve.es/ztnr/3987218.m3u8',
  },
  {
    id: 'La2Canarias.es',
    name: 'La 2 (Canarias)',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Logo_La_2_Canarias.png/960px-Logo_La_2_Canarias.png',
    category: 'Spain',
    url: 'https://ztnr.rtve.es/ztnr/5468585.m3u8',
  },
  {
    id: 'gol.es',
    name: 'GOL TV',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/GolTV.svg/1920px-GolTV.svg.png',
    category: 'Fútbol',
    url: 'http://23.237.104.106:8080/USA_GOLTV/index.m3u8',
  },
  {
    id: 'gol-classics.es',
    name: 'GOL Classics',
    logo: 'https://github.com/Ignac16/Iptv-spain-m3u-1416/blob/main/assets/gol_classics.png?raw=true',
    category: 'Fútbol',
    url: 'https://d71gqtnep83vb.cloudfront.net/gol_classics/gol_classics.m3u8',
  },
];

export const getChannelsByCategory = (): Record<string, Channel[]> => {
  const grouped: Record<string, Channel[]> = {};
  
  channels.forEach((channel) => {
    if (!grouped[channel.category]) {
      grouped[channel.category] = [];
    }
    grouped[channel.category].push(channel);
  });
  
  return grouped;
};

export const getCategories = (): string[] => {
  const categories = new Set(channels.map((channel) => channel.category));
  return Array.from(categories).sort();
};
